
import { GoogleGenAI } from "@google/genai";
import { MODEL_NAME } from "../constants";

const apiKey = process.env.API_KEY || '';
const ai = new GoogleGenAI({ apiKey });

export const generateSpriteImage = async (userPrompt: string): Promise<string> => {
  if (!apiKey) {
    throw new Error("API Key is missing.");
  }

  const systemPrompt = `
    A single full-body character sprite of a ${userPrompt}, pixel art style, super-deformed chibi proportions.
    
    BACKGROUND INSTRUCTION:
    Generate the sprite on a SOLID MAGENTA (#FF00FF) background.
    Do NOT use White, Black, or Gray for the background.
    
    CRITICAL DETAIL - EYES & FACE:
    The eyes must be large and distinct, occupying a 3x3 pixel grid each.
    - The Left 1x3 vertical strip of the eye must be pure WHITE highlights.
    - The Right 2x3 block of the eye must be the colored iris.
    - The face structure must be clear and defined.
    
    The character must be facing forward in a standing idle pose.
    Flat shading, no gradients, heavy outlines to separate from background. High contrast.
    The character should fill the vertical frame (32x48) but leave small padding at top and bottom.
    Do NOT generate a sprite sheet or grid. Generate one large character.
  `;

  try {
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: {
        parts: [
            { text: systemPrompt }
        ]
      },
      config: {
        imageConfig: {
            aspectRatio: "3:4", 
        }
      }
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
      }
    }
    
    throw new Error("No image generated by the model.");
  } catch (error) {
    console.error("Gemini Generation Error:", error);
    throw error;
  }
};

export const generateAnimationSheet = async (baseSpriteBase64: string, userPrompt: string): Promise<string> => {
    if (!apiKey) throw new Error("API Key is missing.");

    const systemPrompt = `
      You are an expert 8-bit sprite animator. 
      I will provide a base character sprite. 
      Generate a 3x3 Grid Sprite Sheet (9 frames total) based on this character.
      
      CONSISTENCY RULES:
      - The FACE, EYES, and HEAD SHAPE must remain PIXEL-PERFECT IDENTICAL to the base sprite in all frames.
      - Maintain the EXACT palette and proportions.
      - Background must be SOLID MAGENTA (#FF00FF).
      
      CRITICAL - WALK CYCLE RULES:
      - Do NOT add new weapons. If the base sprite holds a sword, keep it. If empty handed, STAY empty handed.
      - Arms swinging, legs moving.
      
      GRID LAYOUT (Read carefully):
      Row 1: 
       - Frame 1: Walk Pose A (Left foot forward)
       - Frame 2: Walk Pose B (Right foot forward)
       - Frame 3: Jump Pose (Static, arms up/knees bent)
       
      Row 2: 
       - Frame 4: Special Move Frame 1 (Start of action: ${userPrompt})
       - Frame 5: Special Move Frame 2
       - Frame 6: Special Move Frame 3
       
      Row 3:
       - Frame 7: Special Move Frame 4
       - Frame 8: Special Move Frame 5
       - Frame 9: Special Move Frame 6 (End)
       
      Note: Idle animation is NOT needed (handled via code). Focus on Walk and Special.
      Ensure clear separation between frames.
    `;

    try {
        const cleanBase64 = baseSpriteBase64.replace(/^data:image\/(png|jpeg|jpg);base64,/, '');

        const response = await ai.models.generateContent({
            model: MODEL_NAME,
            contents: {
                parts: [
                    { text: systemPrompt },
                    { inlineData: { mimeType: 'image/png', data: cleanBase64 } }
                ]
            },
            config: {
                imageConfig: {
                    aspectRatio: "1:1", // Square for a 3x3 grid
                }
            }
        });

        for (const part of response.candidates?.[0]?.content?.parts || []) {
            if (part.inlineData) {
                return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
            }
        }
        
        throw new Error("No animation sheet generated.");
    } catch (error) {
        console.error("Gemini Animation Error:", error);
        throw error;
    }
}

export const generateTileset = async (userPrompt: string): Promise<string> => {
  if (!apiKey) throw new Error("API Key is missing.");

  const systemPrompt = `
    Generate a 4x4 Grid Tileset (16 unique tiles total) for a top-down 8-bit RPG game.
    Theme: ${userPrompt}
    
    Each tile is 32x32 pixels. The total image should be square.
    
    CONTENTS (Mix of these):
    - Floor/Ground textures (Grass, Dirt, Stone, Wood)
    - Walls/Obstacles (Brick, Rock, Tree base, Water)
    - Decorative items (Flowers, Cracks, Pebbles)
    
    STYLE:
    - 8-bit pixel art.
    - Flat top-down perspective.
    - High contrast.
    
    BACKGROUND:
    - SOLID MAGENTA (#FF00FF) for any transparent areas.
    - Full tile coverage is preferred for ground tiles.
  `;

  try {
      const response = await ai.models.generateContent({
          model: MODEL_NAME,
          contents: {
              parts: [{ text: systemPrompt }]
          },
          config: {
              imageConfig: {
                  aspectRatio: "1:1"
              }
          }
      });

      for (const part of response.candidates?.[0]?.content?.parts || []) {
          if (part.inlineData) {
              return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
          }
      }
      
      throw new Error("No tileset generated.");
  } catch (error) {
      console.error("Gemini Tileset Error:", error);
      throw error;
  }
};
