
import { GoogleGenAI } from "@google/genai";
import { MODEL_NAME, SPRITE_HEIGHT, SPRITE_WIDTH } from "../constants";

const apiKey = process.env.API_KEY || '';
let ai: GoogleGenAI | undefined;

function getAI(): GoogleGenAI {
  if (!apiKey) throw new Error('API Key is missing.');
  ai ??= new GoogleGenAI({ apiKey });
  return ai;
}

export const generateSpriteImage = async (userPrompt: string): Promise<string> => {
  if (!apiKey) {
    throw new Error("API Key is missing.");
  }

  const systemPrompt = `
    A single full-body character sprite of a ${userPrompt}, pixel art style, super-deformed chibi proportions.
    
    BACKGROUND INSTRUCTION:
    Generate the sprite on a SOLID MAGENTA (#FF00FF) background.
    Do NOT use White, Black, or Gray for the background.
    
    CRITICAL DETAIL - EYES & FACE:
    The eyes must be large and distinct, occupying a 3x3 pixel grid each.
    - The Left 1x3 vertical strip of the eye must be pure WHITE highlights.
    - The Right 2x3 block of the eye must be the colored iris.
    - The face structure must be clear and defined.
    
    The character must be facing forward in a standing idle pose.
    Flat shading, no gradients, heavy outlines to separate from background. High contrast.
    The character should fill the vertical frame (32x48) but leave small padding at top and bottom.
    Do NOT generate a sprite sheet or grid. Generate one large character.
  `;

  try {
    const response = await getAI().models.generateContent({
      model: MODEL_NAME,
      contents: {
        parts: [
            { text: systemPrompt }
        ]
      },
      config: {
        imageConfig: {
            aspectRatio: "3:4", 
        }
      }
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
      }
    }
    
    throw new Error("No image generated by the model.");
  } catch (error) {
    console.error("Gemini Generation Error:", error);
    throw error;
  }
};

export interface AnimationGrid {
  columns: number;
  rows: number;
  aspectRatio: '1:1' | '3:4' | '4:3' | '16:9' | '9:16';
}

/** Pick a compact grid whose cell count exactly matches the requested frames. */
export function getAnimationGrid(frameCount: number): AnimationGrid {
  if (!Number.isInteger(frameCount) || frameCount < 1) {
    throw new Error('Animation frame count must be a positive integer.');
  }
  const choices: AnimationGrid['aspectRatio'][] = ['3:4', '1:1', '4:3', '16:9', '9:16'];
  const ratio = (value: string) => {
    const [width, height] = value.split(':').map(Number);
    return width / height;
  };
  const layouts = choices.flatMap((aspectRatio) => {
    const wantedRatio = ratio(aspectRatio);
    return Array.from({ length: frameCount }, (_, index) => index + 1)
      .filter((columns) => frameCount % columns === 0)
      .map((columns) => {
        const rows = frameCount / columns;
        const targetRatio = (columns * SPRITE_WIDTH) / (rows * SPRITE_HEIGHT);
        return {
          columns,
          rows,
          aspectRatio,
          error: Math.abs(Math.log(wantedRatio / targetRatio)),
        };
      });
  });
  const best = layouts.reduce((winner, layout) => layout.error < winner.error ? layout : winner);
  return { columns: best.columns, rows: best.rows, aspectRatio: best.aspectRatio };
}

/** Generate only the animation the user requested, in row-major frame order. */
export const generateAnimationFrames = async (
  baseSpriteBase64: string,
  animationName: string,
  animationPrompt: string,
  frameCount: number,
  grid: AnimationGrid
): Promise<string> => {
  if (!apiKey) throw new Error('API Key is missing.');

  const systemPrompt = `
    You are an expert pixel-art character animator. The attached image is the exact reference character.
    Create one sprite sheet containing exactly ${frameCount} sequential frames for the "${animationName}" animation.
    The animation action is: ${animationPrompt}

    Arrange the frames in a ${grid.columns}-column by ${grid.rows}-row grid, reading left to right and then top to bottom.
    Each cell contains one complete, centered, full-body pose of the same character. Use every cell exactly once.
    Keep the character's identity, outfit, colors, proportions, outline, and pixel-art style consistent with the reference.
    Do not add props, weapons, or effects that are not in the reference. Use a solid #FF00FF background.
    Leave a small gap between cells. Do not add borders, labels, numbers, or extra frames.
  `;

  const cleanBase64 = baseSpriteBase64.replace(/^data:image\/(png|jpeg|jpg);base64,/, '');
  const response = await getAI().models.generateContent({
    model: MODEL_NAME,
    contents: {
      parts: [
        { text: systemPrompt },
        { inlineData: { mimeType: 'image/png', data: cleanBase64 } },
      ],
    },
    config: { imageConfig: { aspectRatio: grid.aspectRatio } },
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
  }
  throw new Error('No animation frames were generated.');
};
